from fastapi import APIRouter, HTTPException, Response
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from typing import Dict
from io import BytesIO
from fpdf import FPDF
from services.gemini import GeminiReportGenerator

router = APIRouter()
gemini_service = GeminiReportGenerator()

class ReportRequestSchema(BaseModel):
    location: str
    flood_area: str
    veg_loss: str
    road_damage: str
    settlements: str
    severity: str
    confidence: str


@router.post("/generate")
async def generate_ai_report(request: ReportRequestSchema):
    """Invokes Google Gemini SDK to compile natural-language assessment reports based on geospatial metrics"""
    metrics = {
        "location": request.location,
        "flood_area": request.flood_area,
        "veg_loss": request.veg_loss,
        "road_damage": request.road_damage,
        "settlements": request.settlements,
        "severity": request.severity,
        "confidence": request.confidence
    }
    
    report_text = gemini_service.generate_disaster_report(metrics)
    return {
        "location": request.location,
        "generated_report_markdown": report_text
    }


class ISROReportPDF(FPDF):
    """Custom PDF compiler matching ISRO NRSC publication design patterns"""
    def header(self):
        # Draw Border
        self.rect(5, 5, 200, 287)
        # Title Header
        self.set_font('helvetica', 'B', 10)
        self.set_text_color(2, 132, 199) # Blue
        self.cell(0, 5, 'BHARATIYA ANTARIKSH HACKATHON 2026 - CLOUDFREE.AI', ln=1, align='L')
        self.set_font('helvetica', 'B', 8)
        self.set_text_color(249, 115, 22) # Orange
        self.cell(0, 5, 'NATIONAL REMOTE SENSING CENTRE (NRSC) • EARTH OBSERVATION INTELLIGENCE BRIEF', ln=1, align='L')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(100, 116, 139)
        self.cell(0, 10, f'Page {self.page_no()} | Technical Brief generated by CloudFreeAI Spatial Core Engine', align='C')


@router.get("/download/pdf/{scene_key}")
async def download_pdf_report(scene_key: str):
    """Compiles and streams a formatted PDF document containing the disaster intelligence summary"""
    # Grab static scene details
    scenes = {
        "kerala": {
            "name": "Kerala Coastal Plains",
            "severity": "CRITICAL",
            "flood": "42.8 sq km",
            "veg": "18.4%",
            "road": "12.45 km",
            "settlements": "148 villages",
            "conf": "92.4%"
        },
        "uttarakhand": {
            "name": "Uttarakhand Mountain Valleys",
            "severity": "HIGH",
            "flood": "4.2 sq km",
            "veg": "32.1%",
            "road": "3.80 km",
            "settlements": "12 hamlets",
            "conf": "88.7%"
        },
        "chennai": {
            "name": "Chennai Basin Metro",
            "severity": "CRITICAL",
            "flood": "56.1 sq km",
            "veg": "8.2%",
            "road": "28.60 km",
            "settlements": "842 blocks",
            "conf": "94.1%"
        }
    }
    
    key = scene_key.lower().strip()
    if key not in scenes:
        raise HTTPException(status_code=404, detail="Incident scene key not found in records.")
        
    scene = scenes[key]

    # Initialize FPDF
    pdf = ISROReportPDF()
    pdf.add_page()
    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(30, 41, 59) # Slate

    # Report Title
    pdf.set_font("helvetica", "B", 14)
    pdf.cell(0, 10, f"DISASTER ASSESSMENT: {scene['name'].upper()}", ln=1, align="L")
    pdf.set_font("helvetica", "", 8)
    pdf.cell(0, 5, "COREGISTRATION & RECONSTRUCTION PIPELINE: COMPLETED", ln=1)
    pdf.ln(10)

    # Core Telemetry Section
    pdf.set_font("helvetica", "B", 11)
    pdf.cell(0, 7, "1. SENSOR & RECONSTRUCTION TELEMETRY", ln=1)
    pdf.set_font("helvetica", "", 9)
    pdf.cell(0, 6, f"Primary Spacecraft Source: Resourcesat-2 LISS-IV (5.8m Multispectral)", ln=1)
    pdf.cell(0, 6, f"Secondary Structural Sensor: Sentinel-1 SAR (VV+VH Amplitude)", ln=1)
    pdf.cell(0, 6, f"Mean Pixel Reconstruction Confidence: {scene['conf']}", ln=1)
    pdf.cell(0, 6, f"Assigned Hazard Severity Level: {scene['severity']}", ln=1)
    pdf.ln(10)

    # Damaged statistics table
    pdf.set_font("helvetica", "B", 11)
    pdf.cell(0, 7, "2. DETECTED GEOMORPHIC & INFRASTRUCTURE DAMAGE", ln=1)
    pdf.ln(2)
    
    # Headers
    pdf.set_font("helvetica", "B", 9)
    pdf.cell(50, 7, "Parameter Metric", border=1)
    pdf.cell(50, 7, "Assessed Value", border=1)
    pdf.cell(80, 7, "Sensor Verification Method", border=1)
    pdf.ln()
    
    # Rows
    pdf.set_font("helvetica", "", 9)
    pdf.cell(50, 6, "Flood Water Spread", border=1)
    pdf.cell(50, 6, scene["flood"], border=1)
    pdf.cell(80, 6, "DeepLabV3+ Segmented SAR Overlay", border=1)
    pdf.ln()
    pdf.cell(50, 6, "Vegetation Loss", border=1)
    pdf.cell(50, 6, scene["veg"], border=1)
    pdf.cell(80, 6, "Temporal NDVI Gradient Delta", border=1)
    pdf.ln()
    pdf.cell(50, 6, "Inundated Roads", border=1)
    pdf.cell(50, 6, scene["road"], border=1)
    pdf.cell(80, 6, "Siamese ViT Spatial Intersect", border=1)
    pdf.ln()
    pdf.cell(50, 6, "Flooded Settlements", border=1)
    pdf.cell(50, 6, scene["settlements"], border=1)
    pdf.cell(80, 6, "Double-Bounce backscatter anomaly", border=1)
    pdf.ln()
    pdf.ln(10)

    # Guidelines / Directives
    pdf.set_font("helvetica", "B", 11)
    pdf.cell(0, 7, "3. CRITICAL EMERGENCY MITIGATION DIRECTIVES", ln=1)
    pdf.set_font("helvetica", "", 9)
    pdf.multi_cell(0, 5, (
        f"1. Immediate Evacuation: Mobilize response teams to coordinates mapping affected {scene['settlements']}.\n"
        f"2. Infrastructure Isolation: Place checkpoints and block traffic across all {scene['road']} of damaged roads.\n"
        f"3. Sentinel Monitoring: Maintain active Sentinel-1 radar orbits at 12-hour repeats to monitor recession velocities."
    ))

    # Output PDF stream
    pdf_buffer = BytesIO()
    pdf_bytes = pdf.output()
    pdf_buffer.write(pdf_bytes)
    pdf_buffer.seek(0)

    return StreamingResponse(
        pdf_buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename=cloudfreeai_report_{key}.pdf"}
    )
